import { createUpstairsDefinition } from './upstairs/definition.js';
import { alleyLevel } from './alley.js';
import { roofLevel } from './roof.js';
import { MORTAL_KOMBAT_CABINET } from './belowClubConfig.js';

// Y up. Upstairs is assembled from A-103 tracing; Below retains V2.1 authoring units.
// Neither coordinate system is surveyed metres. Reconcile meshes and navigation together.
const surface = (id, name, x1, x2, z1, z2) => ({ id, name, x1, x2, z1, z2, y: 0 });
const rampSurface = (id, name, x1, x2, z1, z2, from, to, axis = 'z') => ({
  id,
  name,
  x1,
  x2,
  z1,
  z2,
  priority: 20,
  ramp: { axis, from, to },
});
const anchor = (name, position, radius, action) => ({ name, position, radius, action });
const cameraWall = (id, x1, x2, z1, z2, y1 = 0, y2 = 3.3) => ({
  id,
  x1,
  x2,
  z1,
  z2,
  y1,
  y2,
  player: false,
});

export const levels = {
  upstairs: createUpstairsDefinition(),
  alley: alleyLevel,
  roof: roofLevel,
  downstairs: {
    id: 'downstairs',
    title: 'DOWNSTAIRS — BELOW BREAKGLASS',
    model: 'below-building',
    provenance: {
      status: 'A-102-informed playable blockout',
      reference: 'Breakglass Studios - FULL FLOOR PLANS PACKAGE.pdf / A-102',
      note: 'Plan-informed room relationships; detailed wall/collision reconciliation is still ongoing.',
    },
    background: 0x060408,
    fog: [18, 58],
    cameraOffset: [4.2, 3.0, 4.6],
    camera: {
      mode: 'close',
      fov: 67,
      distance: 3.7,
      minDistance: 2.1,
      maxDistance: 6.2,
      pitch: 0.34,
      targetHeight: 1.34,
    },
    lights: [
      { color: 0x8749d6, intensity: 3.2, distance: 8, position: [-6.6, 2.2, -2.5] },
      { color: 0xffb06b, intensity: 2.8, distance: 7, position: [-8.1, 2.35, 1.65] },
      { color: 0xff7f50, intensity: 2.2, distance: 6, position: [7.45, 2.2, 4.7] },
    ],
    lightingRig: {
      preset: 'warmup',
      palette: 'breakglass',
      haze: 0.42,
      hazeFar: 10.5,
      hazeVolume: {
        x1: -5.55,
        x2: 5.55,
        y1: 0.35,
        y2: 2.6,
        z1: -3.0,
        z2: 3.0,
        count: 22,
      },
      fixtures: [
        {
          name: 'club-west-red',
          color: 0xff253f,
          intensity: 5.6,
          distance: 15,
          position: [-4.9, 2.7, -2.55],
          phase: 0,
        },
        {
          name: 'club-east-magenta',
          color: 0xff3bc8,
          intensity: 4.8,
          distance: 15,
          position: [4.8, 2.8, -2.4],
          phase: 1.7,
        },
        {
          name: 'club-west-violet',
          color: 0x6f4cff,
          intensity: 5.2,
          distance: 15,
          position: [-4.7, 2.5, 2.45],
          phase: 3.2,
        },
        {
          name: 'club-east-blue',
          color: 0x2c74ff,
          intensity: 4.6,
          distance: 15,
          position: [4.7, 2.45, 2.5],
          phase: 4.9,
        },
        {
          name: 'booth-wash',
          color: 0xff2a55,
          intensity: 3.8,
          distance: 10,
          position: [1.5, 2.7, -2.45],
          phase: 2.4,
        },
      ],
      strobe: { color: 0xffffff, intensity: 11, distance: 13, position: [0, 3.0, 0] },
      laser: {
        color: 0x55ffd8,
        position: [1.5, 2.55, -2.45],
        count: 6,
        length: 10,
        tilt: 0.72,
        sweepSpeed: 0.62,
      },
    },
    crowd: {
      start: 72,
      min: 18,
      idle: 28,
      max: 110,
      zones: [
        { x1: -4.7, x2: 4.7, z1: -2.15, z2: 2.75, weight: 8, kind: 'dance' },
        { x1: -5.45, x2: -4.65, z1: -2.25, z2: 2.65, weight: 1.25, kind: 'social' },
        { x1: 4.65, x2: 5.45, z1: -1.8, z2: 2.7, weight: 1.1, kind: 'social' },
        { x1: -9.35, x2: -6.55, z1: 0.0, z2: 3.35, weight: 2.1, kind: 'social' },
        { x1: 6.35, x2: 8.55, z1: 1.05, z2: 5.9, weight: 1.7, kind: 'social' },
      ],
      avoid: [
        { x1: -0.95, x2: 5.15, z1: -3.25, z2: -1.2 },
        { x1: 2.42, x2: 3.48, z1: -3.18, z2: -2.12 },
        { x1: -7.9, x2: -5.25, z1: -3.3, z2: -0.7 },
        { x1: -9.55, x2: -6.5, z1: -1.4, z2: -0.4 },
      ],
    },
    spawns: {
      start: [-5.15, 0, -1.25],
      stairs: [-6.55, 0.78, -2.95],
      alley: [-9.25, -0.72, -0.82],
    },
    intro: [
      'BELOW BREAKGLASS',
      'The club is alive now. Take A Break is east with the Nora photo room beside it; the kitchen bar is west. The bathroom is through the north-wall door between the studio stair and DJ booth. The shared west stair goes up to the studio and turns down to the alley at its bottom landing.',
    ],
    navigation: {
      surfaces: [
        surface('club', 'Below Breakglass', -5.85, 5.85, -3.25, 3.25),
        surface('bathroom', 'Below bathroom', -5.0, -1.7, -6.45, -3.2),
        surface('service', 'Kitchen + Bar', -9.75, -6.25, -0.25, 3.6),
        surface('bar-door', 'Bar Doorway', -6.5, -5.65, 0.45, 1.4),
        surface('storage', 'Storage', -5, 1.8, 3.35, 6.2),
        surface('lounge', 'Take A Break', 6.2, 8.8, 0.8, 6.15),
        surface('lounge-door', 'Take A Break Doorway', 5.65, 6.5, 1.35, 2.8),
        surface('east-service', 'Nora Photo Room / Production', 6.2, 8.8, -2.7, 0.8),
        surface('coat-check', 'Clark Emergency Exit', 3.55, 5.65, -5.35, -3.2),
        rampSurface(
          'clark-emergency-stairs',
          'Clark emergency exit stair',
          3.82,
          5.38,
          -5.2,
          -3.4,
          0.72,
          0,
        ),
        rampSurface(
          'alley-stairs',
          'Stairs down to alley',
          -9.2,
          -6.8,
          -1.28,
          -0.48,
          -0.72,
          0,
          'x',
        ),
        {
          id: 'alley-stair-bottom',
          name: 'Alley stair lower landing',
          x1: -9.45,
          x2: -9.15,
          z1: -1.28,
          z2: -0.48,
          y: -0.72,
          priority: 21,
        },
        rampSurface(
          'studio-stairs',
          'Wide Clark stair to studio',
          -7.8,
          -5.3,
          -3.25,
          -0.72,
          0.84,
          0,
        ),
        surface('studio-stair-top', 'Clark stair top landing', -7.8, -5.3, -3.5, -3.2),
      ],
      obstacles: [
        // Camera-only volumes mirror the visible Below walls. The original player traversal is
        // intentionally preserved while the third-person camera is no longer allowed to hide
        // behind architecture that previously existed only as render geometry.
        cameraWall('cam-club-north-west-a', -6.15, -4.05, -3.63, -3.37),
        cameraWall('cam-club-north-west-b', -2.65, 3.6, -3.63, -3.37),
        cameraWall('cam-club-north-east', 5.6, 6.15, -3.63, -3.37),
        { ...cameraWall('bathroom-west-wall', -5.22, -4.98, -6.72, -3.5), player: true },
        { ...cameraWall('bathroom-east-wall', -1.72, -1.48, -6.72, -3.5), player: true },
        { ...cameraWall('bathroom-north-wall', -5.2, -1.5, -6.72, -6.48), player: true },
        {
          ...cameraWall('bathroom-south-west', -5.2, -4.05, -3.63, -3.37),
          player: true,
        },
        {
          ...cameraWall('bathroom-south-east', -2.65, -1.5, -3.63, -3.37),
          player: true,
        },
        {
          ...cameraWall('bathroom-stall-divider-a', -4.1, -4.0, -6.25, -4.92, 0, 2.15),
          player: true,
        },
        {
          ...cameraWall('bathroom-stall-divider-b', -2.73, -2.63, -6.25, -4.92, 0, 2.15),
          player: true,
        },
        cameraWall('cam-club-west-north', -6.23, -5.97, -3.62, -2.08),
        cameraWall('cam-club-west-mid', -6.23, -5.97, -0.58, 0.45),
        cameraWall('cam-club-west-south', -6.23, -5.97, 1.4, 3.62),
        cameraWall('cam-club-east-lower', 5.97, 6.23, -3.62, 1.35),
        cameraWall('cam-club-east-south', 5.97, 6.23, 2.8, 3.62),
        {
          id: 'east-service-wall',
          x1: 5.95,
          x2: 6.25,
          z1: -3.62,
          z2: 1.35,
          y1: 0,
          y2: 3.2,
          camera: false,
        },
        {
          id: 'storage-secret-boundary',
          x1: -5.2,
          x2: 2.0,
          z1: 3.22,
          z2: 3.6,
          y1: 0,
          y2: 3.2,
          camera: false,
        },
        cameraWall('cam-club-south', -6.15, 6.15, 3.37, 3.63),
        cameraWall('cam-lounge-west', -10.13, -9.87, -0.52, 3.92),
        cameraWall('cam-lounge-north', -10.1, -6.15, -0.58, -0.32),
        cameraWall('cam-lounge-south', -10.1, -6.15, 3.72, 3.98),
        cameraWall('cam-lounge-east', -6.33, -6.07, 1.3, 3.92),
        cameraWall('cam-storage-west', -5.23, -4.97, 3.7, 6.58),
        cameraWall('cam-storage-east', 1.77, 2.03, 3.7, 6.58),
        cameraWall('cam-storage-south', -5.2, 2.0, 6.32, 6.58),
        cameraWall('cam-service-east', 8.92, 9.18, -3.05, 6.52),
        cameraWall('cam-service-north', 6.15, 9.18, -3.03, -2.77),
        cameraWall('cam-service-south', 6.15, 9.18, 6.27, 6.53),
        cameraWall('cam-coat-west', 3.32, 3.58, -5.72, -3.68),
        cameraWall('cam-coat-east', 5.62, 5.88, -5.72, -3.68),
      ],
    },
    anchors: {
      dj: anchor('DJ booth', [1.5, 0, -2.15], 2.05, 'dj'),
      bathroomStall1: {
        ...anchor('Stall 1 toilet', [-4.52, 0, -5.35], 1.0, 'bathroomFixture'),
        fixtureKind: 'toilet',
        fixtureId: 'stall-1',
      },
      bathroomStall2: {
        ...anchor('Stall 2 toilet', [-3.16, 0, -5.35], 1.0, 'bathroomFixture'),
        fixtureKind: 'toilet',
        fixtureId: 'stall-2',
        clogged: true,
      },
      bathroomUrinal: {
        ...anchor('Urinal', [-1.95, 0, -5.38], 0.95, 'bathroomFixture'),
        fixtureKind: 'urinal',
        fixtureId: 'urinal',
      },
      bathroomSink: {
        ...anchor('Bathroom sink', [-4.45, 0, -4.08], 1.0, 'bathroomFixture'),
        fixtureKind: 'sink',
        fixtureId: 'sink',
      },
      bathroomPlunger: {
        ...anchor('Plunger', [-2.82, 0, -5.05], 0.95, 'bathroomPlunge'),
        fixtureId: 'plunger',
      },
      lightingDesk: anchor('Lighting desk controls', [4.28, 0, -1.62], 1.15, 'clubLighting'),
      ledWallDesk: anchor('Visuals / VJ controls', [4.55, 0, -2.3], 1.15, 'ledWall'),
      killy: anchor('Killy · lighting', [3.72, 0, -0.9], 1.25, 'dialogue'),
      stairs: {
        ...anchor('Stairs upstairs', [-6.55, 0.82, -3.0], 1.55, 'travel'),
        target: 'upstairs',
        requires: 'studioAccessGranted',
      },
      alleyExit: {
        ...anchor('Stairs ↓ Alleyway', [-9.25, -0.72, -0.82], 1.35, 'travel'),
        target: 'alley@clubDoor',
      },
      clarkEmergencyExit: anchor(
        'Clark emergency exit',
        [4.6, 0.64, -5.0],
        1.3,
        'clarkEmergencyExit',
      ),
      nora: anchor('Nora', [-2.5, 0, 1.3], 1.2, 'dialogue'),
      jashim: anchor('Jashim', [-0.7, 0, 0.6], 1.2, 'dialogue'),
      courtney: anchor('Courtney', [-8.72, 0, 3.18], 1.2, 'dialogue'),
      simla: anchor('Simla', [-7.58, 0, 3.18], 1.2, 'dialogue'),
      coffeeMachine: anchor('Kitchen coffee machine', [-9.18, 0, 2.55], 1.35, 'coffee'),
      scoreboard: anchor('Breakglass scoreboard', [-9.45, 0, 0.9], 1.35, 'scoreboard'),
      devin: anchor('Devin', [-4.95, 0, 2.7], 1.2, 'dialogue'),
      installation: anchor(
        'Spatial experiences / installation controls',
        [7.5, 0, 3.5],
        3.2,
        'installation',
      ),
      studioSongPlayer: {
        ...anchor('Take A Break · studio song playback', [8.45, 0, 5.72], 1.4, 'studioSongPlayer'),
        location: 'Take A Break',
      },
      arcade: anchor('Mortal Kombat II cabinet', MORTAL_KOMBAT_CABINET, 1.45, 'arcade'),
      photoWall: anchor('Nora photo wall', [8.35, 0, -1.05], 1.7, 'photoWall'),
      storagePassage: anchor(
        'Overstuffed furniture panel',
        [-2.15, 0, 3.03],
        1.45,
        'storagePassage',
      ),
      storageExit: anchor('Back through the furniture wall', [-2.15, 0, 3.78], 1.35, 'storageExit'),
    },
    npcs: [
      {
        id: 'nora',
        name: 'Nora',
        anchor: 'nora',
        role: 'photographer',
        route: [
          [-2.5, 0, 1.3],
          [0.2, 0, 2.0],
          [3.5, 0, -0.7],
          [6.8, 0, 3.9],
          [7.9, 0, 5.45],
          [-2.5, 0, 1.3],
        ],
        speed: 0.56,
      },
      {
        id: 'james',
        name: 'James',
        position: [-4.6, 0, -1.3],
        role: 'host',
        route: [
          [-4.6, 0, -1.3],
          [-1.2, 0, -0.5],
          [4.4, 0, 1.6],
          [6.5, 0, -0.4],
          [-7.0, 0, 1.9],
        ],
        speed: 0.46,
      },
      {
        id: 'zander',
        name: 'Zander',
        role: 'tech',
        position: [-5.42, 0, -1.42],
        rotationY: -Math.PI / 2,
      },
      {
        id: 'david',
        name: 'David',
        position: [-3.55, 0, 2.55],
        role: 'furniture-dealer',
        color: 0x725a48,
        rotationY: Math.PI,
      },
      { id: 'jashim', name: 'Jashim', anchor: 'jashim', role: 'artist', color: 0x60728f },
      {
        id: 'courtney',
        name: 'Courtney',
        anchor: 'courtney',
        role: 'bartender',
        color: 0x8b5e83,
        rotationY: Math.PI,
      },
      {
        id: 'simla',
        name: 'Simla',
        anchor: 'simla',
        role: 'bartender',
        color: 0x5a806a,
        rotationY: Math.PI,
      },
      {
        id: 'devin',
        name: 'Devin',
        anchor: 'devin',
        role: 'tech',
        route: [
          [-4.95, 0, 2.7],
          [-3.9, 0, -1.5],
          [3.8, 0, 2.2],
          [-4.95, 0, 2.7],
        ],
        speed: 0.38,
        color: 0x4b6e7d,
      },
      {
        id: 'killy',
        name: 'Killy',
        anchor: 'killy',
        role: 'lighting',
        color: 0x6655a8,
        rotationY: -Math.PI / 2,
      },
      { id: 'friend', position: [2.8, 0, 0.7], color: 0x7e5b78, interactive: false },
    ],
  },
};

export const LEVEL_IDS = Object.keys(levels);
